module.exports = {
    CLEAR: 'CLEAR',
    MAROON: 'MAROON',
    LIGHTGRAY: 'LIGHTGRAY',
    PURPLE: 'PURPLE',
    NAVYBLUE: 'NAVYBLUE',
    DARKGREEN: 'DARKGREEN',
    BROWN: 'BROWN',
    TEAL: 'TEAL'
}