module.exports = {
    START_GAME: 'START_GAME',
    PAUSE_GAME: 'PAUSE_GAME',
    UNPAUSE_GAME: 'UNPAUSE_GAME',
    TICK_GAME: 'TICK_GAME',
    SET_CURRENT_PIECE: 'SET_CURRENT_PIECE',
    ROTATE_PIECE: 'ROTATE_PIECE',
    SET_TICK_TIME: 'SET_TICK_TIME',
    MOVE_LEFT: 'MOVE_LEFT',
    MOVE_RIGHT: 'MOVE_RIGHT',
    DROP_PIECE: 'DROP_PIECE',
};